# Generated by Django 6.0.4 on 2026-04-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я/Назва виконавця")),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва жанру')),
                ('description', models.TextField(blank=True, verbose_name='Опис жанру')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва треку')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (якщо платний)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний для прослуховування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.category', verbose_name='Жанр')),
            ],
        ),
    ]
